import React, { Component } from 'react';
import TcsImg from './tcs.jpg';
import Tcs2 from './Tcs2.png';
import Tcs3 from './Tcs3.jpg'
class Tcs extends Component {
  render() {
    return (
      <React.Fragment>
        <div id='list-example' className='list-group'>
          <a className='list-group-item list-group-item-action' href='#about'>
            About{' '}
          </a>

          <a
            className='list-group-item list-group-item-action'
            href='#syllabus'
          >
            Syllabus
          </a>
          <a
            className='list-group-item list-group-item-action'
            href='#criteria'
          >
            Eligibility criteria
          </a>
          <a
            className='list-group-item list-group-item-action'
            href='./InfyLearn'
          >
            What will I learn?
          </a>
          <a className='list-group-item list-group-item-action' href=''>
            Course schedule
          </a>
        </div>
        <div style={{ marginLeft: '250px' }}>
          <div className='row'>
            <div className='column'>
              <img
                src={TcsImg}
                style={{ height: '300px', width: '100%' }}
              />
            </div>
            <div className='column'>
              <img
                src={Tcs2}
                style={{  height: '300px', width: '100%' }}
              />
            </div>
            <div className='column'>
              <img
                src={Tcs3}
                style={{  height: '300px', width: '100%' }}
              />
            </div>
          </div>

          <h3 style={{ color: 'blue' }}>
            <a name='about'>About Tata Consultancy Services</a>
          </h3>
          <p style={{ fontSize: '20px' }}>
            Tata Consultancy Services Limited (TCS) is an Indian multinational
            information technology (IT) service, consulting company
            headquartered in Mumbai, Maharashtra.
            <br />
            It is part of the Tata Group and operates in 46 countries.
            <br />
            TCS is one of the largest Indian companies by market capitalization.
            <br />
            TCS is now placed among the most valuable IT services brands
            worldwide.In 2015, TCS is ranked 64th overall in the Forbes World's
            Most Innovative Companies ranking, making it both the highest-ranked
            IT services company and the top Indian company.[8] It is the world's
            2nd largest IT services provider.
            <br />
            As of 2017, it is ranked 10th on the Fortune India 500 list.
            <br />
            In April 2018, TCS became the first Indian IT company to breach $100
            billion market capitalization, and second Indian company ever (after
            Reliance Industries achieved it in 2007)after its m-cap stood at Rs
            6,79,332.81 crore ($102.6 billion) in Bombay Stock Exchange. In
            2016-2017, Parent company Tata Sons owned 70% of TCS;and more than
            70% of Tata Sons' dividends were generated by TCS.
            <br />
            In March 2018, Tata Sons decided to sell stocks of TCS worth $1.25
            billion in a bulk deal.
            <br />
          </p>
          <h3 style={{ color: 'blue' }}>
            <a name='syllabus'>Syllabus</a>
          </h3>
          <p style={{ fontSize: '20px' }}>
            The format of National Qualifier Test Exam Sections: <br />
            1.English
            <br />
            2. Quantitative Aptitude
            <br />
            3.Programming Concepts & Coding Test <br />
            Negative marking
            <br />
            Duration: 90 minutes
            <br />
          </p>
          <h3 style={{ color: 'blue' }}>
            <a name='criteria'>Eligibility Criteria</a>
          </h3>
          <p style={{ fontSize: '20px' }}>
            1.60% throughout (10th, 12th, UG, PG (If applicable))
            <br />
            2.Maximum 1 active backlog
            <br />
            3.Maximum 24 months' gap (if any - Only in between education and not
            during education)
            <br />
            4.Qualification: Full Time Graduates from B.E / B.Tech / M.E /
            M.Tech / MCA - 2019 batch only
            <br />
            5.Specialization: B.E/B.Tech/M.E/M.Tech - All Specializations | M.Sc
            - Computer Science/Information Technology and other related
            disciplines | MCA with B.Sc/BCA/B.Com/BA (with Mathematics/
            Statistics).
            <br />
            6.Criteria: the candidate applying for the test needs to have a
            minimum aggregate of 60% throughout Class X, XII, Diploma (if
            applicable), UG & PG (if applicable).
            <br />
            7.Academic Gap: the overall gap in academics should not exceed 2
            years.
            <br />
          </p>
          <br />
        </div>
      </React.Fragment>
    );
  }
}
export default Tcs;
